name: Daily India Financial News

on:
  schedule:
      - cron: "0 * * * *"
  
  workflow_dispatch:       # Allow manual run

jobs:
  run-news-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install feedparser

      - name: Run script
        run: |
          python india_news.py

      - name: Commit & Push results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Updated daily news" || echo "Nothing to commit"
          git push
